// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        if (!androidConfigured) {
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for android - '
            'fill in DefaultFirebaseOptions.android below.',
          );
        }
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuz-oW01scCnmNj4pnmjAvPKft14daJWM',
    appId: '1:54906570613:web:9e8530ba8381686cd6b53c',
    messagingSenderId: '54906570613',
    projectId: 'odon-dashboard-fin',
    authDomain: 'odon-dashboard-fin.firebaseapp.com',
    storageBucket: 'odon-dashboard-fin.firebasestorage.app',
  );

  /// The Android app registered in the SAME Firebase project as the web app
  /// (odon-dashboard-fin), package com.example.odon_booking. The backend only
  /// accepts sign-ins from that project.
  ///
  /// Copy apiKey and appId from that app's google-services.json:
  ///   apiKey -> client[0].api_key[0].current_key
  ///   appId  -> client[0].client_info.mobilesdk_app_id
  ///
  /// If these are ever emptied the Android app runs without sign-in, and its
  /// bookings are saved without a name.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAVF6lTXH_uZnIYpjqkFDBpdoulmge34Y',
    appId: '1:54906570613:android:931e7ed941c279a8d6b53c',
    messagingSenderId: '54906570613',
    projectId: 'odon-dashboard-fin',
    storageBucket: 'odon-dashboard-fin.firebasestorage.app',
  );

  static bool get androidConfigured =>
      android.apiKey.isNotEmpty && android.appId.isNotEmpty;

  /// Options for the platform the app is running on, or null where sign-in is
  /// not set up (iOS/desktop, or Android before the values above are filled).
  static FirebaseOptions? get signInPlatform {
    if (kIsWeb) return web;
    if (defaultTargetPlatform == TargetPlatform.android && androidConfigured) {
      return android;
    }
    return null;
  }
}
